controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_shoulder_pan_joint
      - left_shoulder_shoulder_lift_joint
      - left_shoulder_elbow_joint
      - left_shoulder_wrist_1_joint
      - left_shoulder_wrist_2_joint
      - left_shoulder_wrist_3_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_shoulder_pan_joint
      - right_shoulder_shoulder_lift_joint
      - right_shoulder_elbow_joint
      - right_shoulder_wrist_1_joint
      - right_shoulder_wrist_2_joint
      - right_shoulder_wrist_3_joint
  - name: fake_dual_arms_controller
    joints:
      - left_shoulder_shoulder_pan_joint
      - left_shoulder_shoulder_lift_joint
      - left_shoulder_elbow_joint
      - left_shoulder_wrist_1_joint
      - left_shoulder_wrist_2_joint
      - left_shoulder_wrist_3_joint
      - right_shoulder_shoulder_pan_joint
      - right_shoulder_shoulder_lift_joint
      - right_shoulder_elbow_joint
      - right_shoulder_wrist_1_joint
      - right_shoulder_wrist_2_joint
      - right_shoulder_wrist_3_joint